# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoExam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoExam
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxTest'
  pod 'RxBlocking'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'AlamofireObjectMapper'
  pod 'Swinject'
  pod 'SwinjectStoryboard'

  target 'TodoExamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodoExamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
